// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 使用新的侧边栏 ID，例如 articlesSidebar
  leetcodeAnswerSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;