// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 自动根据 hardware-and-silicon 目录结构生成侧边栏
  hardwareSiliconSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;